### ISSUE TITLE
setup.cfg is missing the 'version' line

### ISSUE THREAD

**Issue by yurivict** [tox-dev/filelock#133]
As a result the installed PKG-INFO lists version as 0.0.0 and the ```tox``` command fails:
```

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 568, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.8/site-packages/pkg_resources/__init__.py", line 777, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (filelock 0.0.0 (/usr/local/lib/python3.8/site-packages), Requirement.parse('filelock<4,>=3.0.0'), {'tox'})
```

**Comment by gaborbernat** [comment]
It's not missing.  We use setuptools-scm to acquire it from the SCM. Please use a pyproject compatible build system and you should have it.
