### ISSUE TITLE
AttributeError: 'UnixFileLock' object has no attribute '_thread_lock'

### ISSUE THREAD

**Issue by JarbasAl** [tox-dev/filelock#137]
started getting this in py 3.10 via https://github.com/forslund/combo-lock

```
Exception ignored in: <function BaseFileLock.__del__ at 0xffffae61dd80>
Traceback (most recent call last):
  File "/home/mycroft/.local/lib/python3.10/site-packages/filelock/_api.py", line 233, in __del__
    self.release(force=True)
  File "/home/mycroft/.local/lib/python3.10/site-packages/filelock/_api.py", line 194, in release
    with self._thread_lock:
AttributeError: 'UnixFileLock' object has no attribute '_thread_lock'
```

**Comment by gaborbernat** [comment]
That seems like shouldn't happen can you post a reproducible of it? (ideally a docker image)

**Comment by JarbasAl** [comment]
I didn't yet have the time to dig into this error, i am not sure how to reproduce this

I get it consistently in ovos-core, which uses json_database, which uses combo_lock, which itself uses filelock. Too many moving pieces to debug... I am involved and very familiar with all those packages and do not see how it can be happening at all

Will follow up with additional info if i find something, for now i am reverting json_database to an older version in order to avoid this issue

Apologies for not being a very useful issue, I have limited bandwidth to dedicate to this right now but i wanted to document this before moving on since it is being a deal breaker to me.

**Comment by gaborbernat** [comment]
I'll close this for now, if you get more information we can reopen.

**Comment by GeniusWiki** [comment]
I also got same error on Python 3.10 and latest FL 3.8.  This libraries is used by Snowflake Python Connector.  The error stack is 
```
2022-11-28T12:20:47.482+11:00	Exception ignored in: <function BaseFileLock.__del__ at 0x7f463264ed40>
2022-11-28T12:20:47.482+11:00	Traceback (most recent call last):
2022-11-28T12:20:47.482+11:00	File "/usr/local/lib/python3.10/dist-packages/filelock/_api.py", line 240, in __del__
2022-11-28T12:20:47.482+11:00	self.release(force=True)
2022-11-28T12:20:47.482+11:00	File "/usr/local/lib/python3.10/dist-packages/filelock/_api.py", line 201, in release
2022-11-28T12:20:47.482+11:00	with self._thread_lock:
2022-11-28T12:20:47.482+11:00	AttributeError: 'UnixFileLock' object has no attribute '_thread_lock'
2022-11-28T12:20:48.896+11:00	Exception ignored in: <function BaseFileLock.__del__ at 0x7f463264ed40>
```
