### ISSUE TITLE
6 tests fail

### ISSUE THREAD

**Issue by yurivict** [tox-dev/filelock#322]
```
========================================================================================= FAILURES ==========================================================================================
_________________________________________________________ test_singleton_locks_must_be_initialized_with_the_same_args[UnixFileLock] _________________________________________________________

lock_type = <class 'filelock._unix.UnixFileLock'>, tmp_path = PosixPath('/tmp/pytest-of-yuri/pytest-27/test_singleton_locks_must_be_i0')

    @pytest.mark.parametrize("lock_type", [FileLock, SoftFileLock])
    def test_singleton_locks_must_be_initialized_with_the_same_args(lock_type: type[BaseFileLock], tmp_path: Path) -> None:
        lock_path = tmp_path / "a"
        lock = lock_type(str(lock_path), is_singleton=True)  # noqa: F841
    
        with pytest.raises(ValueError, match="Singleton lock instances cannot be initialized with differing arguments"):
>           lock_type(str(lock_path), timeout=10, is_singleton=True)
E           Failed: DID NOT RAISE <class 'ValueError'>

tests/test_filelock.py:685: Failed
_____________________________________________________ test_singleton_locks_are_deleted_when_no_external_references_exist[UnixFileLock] ______________________________________________________

lock_type = <class 'filelock._unix.UnixFileLock'>, tmp_path = PosixPath('/tmp/pytest-of-yuri/pytest-27/test_singleton_locks_are_delet0')

    @pytest.mark.skipif(hasattr(sys, "pypy_version_info"), reason="del() does not trigger GC in PyPy")
    @pytest.mark.parametrize("lock_type", [FileLock, SoftFileLock])
    def test_singleton_locks_are_deleted_when_no_external_references_exist(
        lock_type: type[BaseFileLock],
        tmp_path: Path,
    ) -> None:
        lock_path = tmp_path / "a"
        lock = lock_type(str(lock_path), is_singleton=True)
    
>       assert lock_type._instances == {str(lock_path): lock}  # noqa: SLF001
E       AssertionError: assert <WeakValueDic...x38d4654b3e20> == {'/tmp/pytest...38d46561ec40>}
E         Full diff:
E         - {'/tmp/pytest-of-yuri/pytest-27/test_singleton_locks_are_delet0/a': <filelock._unix.UnixFileLock object at 0x38d46561ec40>}
E         + <WeakValueDictionary at 0x38d4654b3e20>

tests/test_filelock.py:699: AssertionError
___________________________________________________________ test_singleton_instance_tracking_is_unique_per_subclass[UnixFileLock] ___________________________________________________________

lock_type = <class 'filelock._unix.UnixFileLock'>

    @pytest.mark.skipif(hasattr(sys, "pypy_version_info"), reason="del() does not trigger GC in PyPy")
    @pytest.mark.parametrize("lock_type", [FileLock, SoftFileLock])
    def test_singleton_instance_tracking_is_unique_per_subclass(lock_type: type[BaseFileLock]) -> None:
        class Lock1(lock_type):  # type: ignore[valid-type, misc]
            pass
    
        class Lock2(lock_type):  # type: ignore[valid-type, misc]
            pass
    
        assert isinstance(Lock1._instances, WeakValueDictionary)  # noqa: SLF001
        assert isinstance(Lock2._instances, WeakValueDictionary)  # noqa: SLF001
>       assert Lock1._instances is not Lock2._instances  # noqa: SLF001
E       AssertionError: assert <WeakValueDictionary at 0x38d4654b3e20> is not <WeakValueDictionary at 0x38d4654b3e20>
E        +  where <WeakValueDictionary at 0x38d4654b3e20> = <class 'test_filelock.test_singleton_instance_tracking_is_unique_per_subclass.<locals>.Lock1'>._instances
E        +  and   <WeakValueDictionary at 0x38d4654b3e20> = <class 'test_filelock.test_singleton_instance_tracking_is_unique_per_subclass.<locals>.Lock2'>._instances

tests/test_filelock.py:715: AssertionError
___________________________________________________________ test_singleton_instance_tracking_is_unique_per_subclass[SoftFileLock] ___________________________________________________________

lock_type = <class 'filelock._soft.SoftFileLock'>

    @pytest.mark.skipif(hasattr(sys, "pypy_version_info"), reason="del() does not trigger GC in PyPy")
    @pytest.mark.parametrize("lock_type", [FileLock, SoftFileLock])
    def test_singleton_instance_tracking_is_unique_per_subclass(lock_type: type[BaseFileLock]) -> None:
        class Lock1(lock_type):  # type: ignore[valid-type, misc]
            pass
    
        class Lock2(lock_type):  # type: ignore[valid-type, misc]
            pass
    
        assert isinstance(Lock1._instances, WeakValueDictionary)  # noqa: SLF001
        assert isinstance(Lock2._instances, WeakValueDictionary)  # noqa: SLF001
>       assert Lock1._instances is not Lock2._instances  # noqa: SLF001
E       AssertionError: assert <WeakValueDictionary at 0x38d4654b3e20> is not <WeakValueDictionary at 0x38d4654b3e20>
E        +  where <WeakValueDictionary at 0x38d4654b3e20> = <class 'test_filelock.test_singleton_instance_tracking_is_unique_per_subclass.<locals>.Lock1'>._instances
E        +  and   <WeakValueDictionary at 0x38d4654b3e20> = <class 'test_filelock.test_singleton_instance_tracking_is_unique_per_subclass.<locals>.Lock2'>._instances

tests/test_filelock.py:715: AssertionError
_________________________________________________________ test_singleton_locks_must_be_initialized_with_the_same_args[SoftFileLock] _________________________________________________________

lock_type = <class 'filelock._soft.SoftFileLock'>, tmp_path = PosixPath('/tmp/pytest-of-yuri/pytest-27/test_singleton_locks_must_be_i1')

    @pytest.mark.parametrize("lock_type", [FileLock, SoftFileLock])
    def test_singleton_locks_must_be_initialized_with_the_same_args(lock_type: type[BaseFileLock], tmp_path: Path) -> None:
        lock_path = tmp_path / "a"
        lock = lock_type(str(lock_path), is_singleton=True)  # noqa: F841
    
        with pytest.raises(ValueError, match="Singleton lock instances cannot be initialized with differing arguments"):
>           lock_type(str(lock_path), timeout=10, is_singleton=True)
E           Failed: DID NOT RAISE <class 'ValueError'>

tests/test_filelock.py:685: Failed
_____________________________________________________ test_singleton_locks_are_deleted_when_no_external_references_exist[SoftFileLock] ______________________________________________________

lock_type = <class 'filelock._soft.SoftFileLock'>, tmp_path = PosixPath('/tmp/pytest-of-yuri/pytest-27/test_singleton_locks_are_delet1')

    @pytest.mark.skipif(hasattr(sys, "pypy_version_info"), reason="del() does not trigger GC in PyPy")
    @pytest.mark.parametrize("lock_type", [FileLock, SoftFileLock])
    def test_singleton_locks_are_deleted_when_no_external_references_exist(
        lock_type: type[BaseFileLock],
        tmp_path: Path,
    ) -> None:
        lock_path = tmp_path / "a"
        lock = lock_type(str(lock_path), is_singleton=True)
    
>       assert lock_type._instances == {str(lock_path): lock}  # noqa: SLF001
E       AssertionError: assert <WeakValueDic...x38d4654b3e20> == {'/tmp/pytest...38d464d1b910>}
E         Full diff:
E         - {'/tmp/pytest-of-yuri/pytest-27/test_singleton_locks_are_delet1/a': <filelock._soft.SoftFileLock object at 0x38d464d1b910>}
E         + <WeakValueDictionary at 0x38d4654b3e20>

tests/test_filelock.py:699: AssertionError
===================================================================================== warnings summary ======================================================================================
tests/test_filelock.py::test_subclass_compatibility
  /usr/local/lib/python3.9/site-packages/_pytest/unraisableexception.py:78: PytestUnraisableExceptionWarning: Exception ignored in: <function BaseFileLock.__del__ at 0x38d4654c2af0>
  
  Traceback (most recent call last):
    File "/usr/local/lib/python3.9/site-packages/filelock/_api.py", line 317, in __del__
      self.release(force=True)
    File "/usr/local/lib/python3.9/site-packages/filelock/_api.py", line 280, in release
      if self.is_locked:
    File "/usr/local/lib/python3.9/site-packages/filelock/_api.py", line 190, in is_locked
      return self._context.lock_file_fd is not None
  AttributeError: 'MySoftFileLock' object has no attribute '_context'
  
    warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
================================================================================== short test summary info ==================================================================================
SKIPPED [20] tests/test_filelock.py:106: Windows only
=================================================================== 6 failed, 81 passed, 20 skipped, 1 warning in 16.30s ====================================================================
*** Error code 1
```

Version: 3.13.4
Python-3.9
FreeBSD 14.0

**Comment by gaborbernat** [comment]
Please post a reproducible using a Docker image demonstrating exactly how you are running the test suite. What you have currently provided is not enough to reproduce.

**Comment by yurivict** [comment]
Docker doesn't support FreeBSD.

[Here](https://freebsd.org/~yuri/filelock-3.13.4-tests.log) is a complete log.

The standard pytest command is run, same as for all other Python-based ports that are tested with PyTest.

**Comment by gaborbernat** [comment]
> Docker doesn't support FreeBSD.

This makes it hard for us to work on. In light of this, I'll say PR fixing this is welcome, but we don't plan to do it. You can fill in a PR without an issue, I'll close this for now, as can't reproduce.

**Comment by gaborbernat** [comment]
> The standard pytest command is run, same as for all other Python-based ports that are tested with PyTest.

We don't support this. You must use tox for testing. You might want to use https://pypi.org/project/tox-current-env/

**Comment by yurivict** [comment]
@gaborbernat 

pyproject.toml lists pytest as a requirement though, and tox isn't mentioned for testing:
```
optional-dependencies.testing = [
  "covdefaults>=2.3",
  "coverage>=7.3.2", 
  "diff-cover>=8.0.1",
  "pytest>=7.4.3",
  "pytest-cov>=4.1",
  "pytest-mock>=3.12",
  "pytest-timeout>=2.2",
]
```

**Comment by gaborbernat** [comment]
> pyproject.toml lists pytest as a requirement though, and tox isn't mentioned for testing:

https://github.com/tox-dev/filelock/blob/main/tox.ini#L19 the fact that we're using it in the CI is proof of that. And just because pytest is a dependency does not mean we accept running it in non-standard ways (that is not through tox).
