### ISSUE TITLE
AttributeError: '_CountedFileLock' object has no attribute 'thread_safe'

### ISSUE THREAD

**Issue by JakeUrban** [tox-dev/filelock#336]
I'm trying to run `poetry install` and I'm getting the following stack trace:

```
Run poetry install
  
Creating virtualenv django-polaris-sWbKydhB-py3.10 in /home/runner/.cache/pypoetry/virtualenvs
object.__init__() takes exactly one argument (the instance to initialize)
Exception ignored in: <function BaseFileLock.__del__ at 0x7ffad06[4](https://github.com/stellar/django-polaris/actions/runs/9487616503/job/26144651170?pr=721#step:5:4)e050>
Traceback (most recent call last):
  File "/usr/local/poetry/lib/python3.10/site-packages/filelock/_api.py", line 365, in __del__
    self.release(force=True)
  File "/usr/local/poetry/lib/python3.10/site-packages/virtualenv/util/lock.py", line 3[4](https://github.com/stellar/django-polaris/actions/runs/9487616503/job/26144651170?pr=721#step:5:5), in release
    with self.thread_safe:
AttributeError: '_CountedFileLock' object has no attribute 'thread_safe'
```

**Comment by JakeUrban** [comment]
I suspect this bug arose in the very-recent 3.15 release

**Comment by sterliakov** [comment]
Same as #337.
