### ISSUE TITLE
the latest filelock package 3.15.1 has compatible issue with package virtualenv

### ISSUE THREAD

**Issue by LiliDeng** [tox-dev/filelock#339]
error is 

```
RuntimeError: failed to build image pip, setuptools, wheel because:
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/virtualenv/seed/embed/via_app_data/via_app_data.py", line 54, in _install
    with parent.non_reentrant_lock_for_key(wheel_img.name):
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/virtualenv/util/lock.py", line 142, in non_reentrant_lock_for_key
    with _CountedFileLock(str(self.path / f"{name}.lock")):
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/virtualenv/util/lock.py", line 22, in __init__
    super().__init__(lock_file)
TypeError: object.__init__() takes exactly one argument (the instance to initialize)

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/virtualenv/seed/embed/via_app_data/via_app_data.py", line 54, in _install
    with parent.non_reentrant_lock_for_key(wheel_img.name):
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/virtualenv/util/lock.py", line 142, in non_reentrant_lock_for_key
    with _CountedFileLock(str(self.path / f"{name}.lock")):
  File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/virtualenv/util/lock.py", line 22, in __init__
    super().__init__(lock_file)
```

**Comment by gaborbernat** [comment]
3.15.1 was released in the meantime and fixes this.

**Comment by LiliDeng** [comment]
> 3.15.1 was released in the meantime and fixes this.

thanks! when the version 3.15.1 will be release?

**Comment by LiliDeng** [comment]
> > 3.15.1 was released in the meantime and fixes this.
> 
> thanks! when the version 3.15.1 will be release?

oh, it has been released, but seems it still has the issue, let me double check

**Comment by LiliDeng** [comment]
@gaborbernat we met this issue in version 3.15.1, we have to use version 3.14.0

**Comment by gaborbernat** [comment]
In that case please post more information, because your original post doesn't show what version you're running and in what way. And no one else ran into this problem with the new version.

**Comment by LiliDeng** [comment]
> In that case please post more information, because your original post doesn't show what version you're running and in what way. And no one else ran into this problem with the new version.

the version 3.15.1 works well, sorry for the confusion, since we use internal feed, need explicit install the latest package once.
