### ISSUE TITLE
Android/Termux doesn't have flock, use lockf, SoftFileLock, or no lock?

### ISSUE THREAD

**Issue by warp9pnt9** [tox-dev/filelock#349]
Similar issue as listed on [yt-dlp](https://github.com/yt-dlp/yt-dlp/issues/2670).

Android/Termux doesn't have flock.
Fallback to lockf or SoftFileLock?
Possibly fallback to no lock?

scdl shown in example uses filelock as a dependency, yt-dlp rolls their own.

filelock's _unix.py incorrectly assumes all Unices have flock, or that Android === Unix.

Note: command line for example only

```
scdl -l https://soundcloud.com/user/track
Soundcloud Downloader
Found a track
Downloading track
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/filelock/_unix.py", line 46, in _acquire
    fcntl.flock(fd, fcntl.LOCK_EX | fcntl.LOCK_NB)
OSError: [Errno 38] Function not implemented

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/scdl", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/scdl/scdl.py", line 304, in main
    download_url(client, **python_args)
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/scdl/scdl.py", line 409, in download_url
    download_track(client, item, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/scdl/scdl.py", line 887, in download_track
    with lock:
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/filelock/_api.py", line 376, in __enter__
    self.acquire()
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/filelock/_api.py", line 332, in acquire
    self._acquire()
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/filelock/_unix.py", line 51, in _acquire
    raise NotImplementedError(msg) from exception
NotImplementedError: FileSystem does not appear to support flock; use SoftFileLock instead
```

**Comment by DJStompZone** [comment]
This error is driving me nuts

"Use softfilelock instead"
Ok yes but HOW??

**Comment by gaborbernat** [comment]
A variant of this issue is also reported in #289  on network volumes (e.g. cluster home directories), `fcntl` imports fine but `flock` fails at runtime with `ENOSYS`. That issue requests an environment variable (e.g. `FILELOCK_FORCE_SOFT=1`) to let users force `SoftFileLock` without code changes, which would be useful for cases where the filesystem limitation is known ahead of time.

Both issues should be addressed together: automatic fallback to `SoftFileLock` on `ENOSYS` (this issue), plus an optional env var override for users who want to skip the `flock` attempt entirely (#289).
