### ISSUE TITLE
Test  failed on Windows

### ISSUE THREAD

**Issue by dkw72n** [tox-dev/filelock#5]
```
H:\>python test.py
..EE......E
======================================================================
ERROR: test_default_timeout (__main__.TestFileLock)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 213, in test_default_timeout
    self.assertRaises(filelock.Timeout, lock2.acquire)
  File "C:\Python27\lib\unittest\case.py", line 475, in assertRaises
    callableObj(*args, **kwargs)
  File "H:\filelock.py", line 230, in acquire
    self._acquire()
  File "H:\filelock.py", line 312, in _acquire
    msvcrt.locking(fd, msvcrt.LK_NBLCK, 1)
IOError: [Errno 13] Permission denied

======================================================================
ERROR: test_del (__main__.TestFileLock)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 265, in test_del
    self.assertRaises(filelock.Timeout, lock2.acquire, timeout = 0)
  File "C:\Python27\lib\unittest\case.py", line 475, in assertRaises
    callableObj(*args, **kwargs)
  File "H:\filelock.py", line 230, in acquire
    self._acquire()
  File "H:\filelock.py", line 312, in _acquire
    msvcrt.locking(fd, msvcrt.LK_NBLCK, 1)
IOError: [Errno 13] Permission denied

======================================================================
ERROR: test_timeout (__main__.TestFileLock)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 192, in test_timeout
    self.assertRaises(filelock.Timeout, lock2.acquire, timeout=1)
  File "C:\Python27\lib\unittest\case.py", line 475, in assertRaises
    callableObj(*args, **kwargs)
  File "H:\filelock.py", line 230, in acquire
    self._acquire()
  File "H:\filelock.py", line 312, in _acquire
    msvcrt.locking(fd, msvcrt.LK_NBLCK, 1)
IOError: [Errno 13] Permission denied

----------------------------------------------------------------------
Ran 11 tests in 0.988s

FAILED (errors=3)
```

According to https://docs.python.org/2/library/msvcrt.html :
 msvcrt.locking "Raises IOError on failure." instead of OSError
 After changing the ''OSError'' to 'IOError', all tests passed.

```
H:\>python test.py
...........
----------------------------------------------------------------------
Ran 11 tests in 3.170s

OK
```

**Comment by AdorablePotato** [comment]
Thank you. They changed this in Python 3.3 and I started developing this module with this version. I have currently no windows machine and therefore I could not test the changes. Please tell me if the tests pass.

**Comment by dkw72n** [comment]
Now all tests are passed. On Windows 7, in both Python 2.7.5 and Python 3.4.2.
